additional commit on lesson 5
Bayheck/Kolesa-Upgrade-FE-2021 pull request #4
Opened 2021-10-11 00:55 UTC by Bayheck

Реализовал функцию добавления карточек по категориям с сортировкой и без отдельного мок массива для всех товаров. Однако со второй частью задания возникли трудности, а именно с делегацией ивентов. Получилось реализовать появление модального окна с данными от той карты с которой оно было вызвано. Можно удалить модальное окно с помощью крестика. Но с этого момента код как то странно начинает себя вести. Отключается возможность переключатся между категориями. И в целом кажется вызывание ивент хэндлера на документ такой себе идеей. Буду рад любой помощи. Ваш фидбэк очень сильно помогает, спасибо.

2021-10-11 10:21 UTC, mushegov requested changes
Не могу принять такуб работу :(

2021-10-11 10:21 UTC, mushegov commented on src/js/main.js
> +/* eslint-disable eqeqeq */
что это?

2021-10-11 10:21 UTC, mushegov commented on src/js/main.js
> +const compare = (a, b) => {
compare слишком абстрактно, лучше sortByNew или как-то так

2021-10-11 10:21 UTC, mushegov commented on src/js/main.js
> +const makeProductCard = (title, image, price, isNew, id) => ` <div class="card" data-index = ${id}>
`<div data-index="${id}">`

2021-10-11 10:21 UTC, mushegov commented on src/js/main.js
> +        const buttoner = event.target;
оверхед, можно просто `const categoryKey = event.target.dataset.key`

2021-10-11 10:21 UTC, mushegov commented on src/js/main.js
> +        if (categoryKey === 'clothes') {
Почти весь код повторяется в каждой ветке. Нужно опмтимизировать.

```
let cards;

if (key = 'clothes') {
  cards = clothes.sort.compare();
}

if (key = 'accessories') {
  cards = accessories.sort.compare();
}

document.querySelector('.js_gallery').innerHTML = '';
cards .forEach(...);
```

Как-то так хотябы

2021-10-11 10:21 UTC, mushegov commented on src/js/main.js
> +                ${id >= 8 ? '' : `Как выбрать размер:<div class="howChooseText">
не, так совсем не пойдет

2021-10-11 23:25 UTC, Bayheck commented
Вроде как удалось реализовать весь основной функционал из дз. Буду рад любому фидбэку. Спасибо.

2021-10-12 04:23 UTC, mushegov approved these changes
Неплохая работа, непонятно почему изначально было так плохо.

Окончательная оценка: 80

2021-10-12 04:23 UTC, mushegov commented on src/js/main.js
> +function onOverlay() {
почему некоторые функции стрелочные а некоторые обычные?

2021-10-12 04:23 UTC, mushegov commented on src/js/main.js
> +    if (event.pointerId === -1) {
двойное событие возникает потому что ты добавил клик на обертку с input-ом
вообще, в твоей реализации верстки с input-ом лучше добавить слушательно на change input-а

2021-10-12 04:23 UTC, mushegov commented on src/js/main.js
> +        clothes.sort(sortByNew);
мутируешь исходные данные. могут возникнуть сайдэффекты.
лучше `cards = [...clothes].sort(sortByNew)`

2021-10-12 04:23 UTC, mushegov commented on src/js/main.js
> +const modalCreator = () => {
лучше что-то в стиле addCardClickEventListener

2021-10-13 11:58 UTC, merged